name: Update Terraform Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .

      - name: Fix permissions
        run: |
          chmod -R ugo+rwX .

      - name: Commit changes to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
